# Generated by Django 5.2 on 2025-04-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='explanation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
